sp: 
  user-service:
    users: "[{\"id\":777, \"username\":\"abcDE\",\"password\":\"123DD\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"},{\"id\":99, \"username\":\"ghi\",\"password\":\"123\"}]"

spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.211.132
    port: 5672
    username: admin
    password: admin
    
server:
  port: 8101
  
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
  
  cloud:
    config:
      override-none: true

management:
  endpoints:
    web:
      exposure:
        include: refresh

#---
#spring:
 # profiles: user1  
#server:
  #port: 8101      
#---
#spring:
  #profiles: user2
#server:
 # port: 8102  
  
  